"""Configuration package for the agentic ecommerce service."""

from configs.agents import (
    ALLOWED_REQUEST_TYPES,
    CATALOG_AGENT_MODEL,
    CATALOG_PLANNER_SYSTEM_PROMPT,
    CLASSIFICATION_PROMPT,
    CLASSIFIER_MODEL,
    DEFAULT_LLM_TEMPERATURE,
    ORDER_PLANNER_SYSTEM_PROMPT,
    ORDER_AGENT_MODEL,
    UNKNOWN_REQUEST_RESPONSE,
)
from configs.configs import (
    ECOM_TOOLS_API_URL,
    HTTP_REQUEST_TIMEOUT,
    LOG_FORMAT,
    LOG_LEVEL,
    MAX_AGENT_ITERATIONS,
    USERS_PAGE_LIMIT,
    USERS_PAGE_OFFSET,
)

__all__ = [
    "CATALOG_AGENT_MODEL",
    "CATALOG_PLANNER_SYSTEM_PROMPT",
    "CLASSIFICATION_PROMPT",
    "CLASSIFIER_MODEL",
    "DEFAULT_LLM_TEMPERATURE",
    "ECOM_TOOLS_API_URL",
    "HTTP_REQUEST_TIMEOUT",
    "LOG_FORMAT",
    "LOG_LEVEL",
    "MAX_AGENT_ITERATIONS",
    "ORDER_AGENT_MODEL",
    "ORDER_PLANNER_SYSTEM_PROMPT",
    "UNKNOWN_REQUEST_RESPONSE",
    "ALLOWED_REQUEST_TYPES",
    "USERS_PAGE_LIMIT",
    "USERS_PAGE_OFFSET",
]
